### PR TITLE
What if linkGrabber try to find links on url address that point to pdf or images?

### PR DESCRIPTION
**Pull request by d555**
It shouldn't try to find links when the content is not textable, so it is necessary to check content-type from the header of the response. And, for other purposes is better to store the response like the chance to retrieve the text as a attribute as well. Some PEP8 styles errores fixed.

### CODE REVIEW

**Comment by neurosnap** [comment]
Greetings!  Thanks for your contribution, quick question: why did you add __init__.py to the .gitignore?

**Comment by d555** [comment]
Hi, It was a mistake, for sure. I didn't see it. I fixed with the last commit. ;)

**Comment by d555** [comment]
the last change fix the errors?

**Comment by neurosnap** [comment]
I'm fixing a few things in the current code base, I'll be merging your PR shortly.

**Comment by neurosnap** [comment]
Thanks for the help :) much appreciated

https://pypi.python.org/pypi/linkGrabber/0.3.0

**Comment by d555** [comment]
Great! I was using my fork for https://github.com/d555/digs. I will updated it, to use this new version.

**Pull request merged**
